server:
  undertow:
    threads:
      worker: 10
      io: 2

logging:
  level:
    com.kaua.payment.infrastructure: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/payments-database
    username: postgres
    password: 123456
  jpa:
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration