version: '3.7'

services:
  postgres:
    container_name: payments-ms_postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=payments-database
      - POSTGRES_PASSWORD=123456
    ports:
      - "5433:5432"